#!/usr/bin/env bash

sudo apt install libfuse2
wget https://github.com/neovim/neovim/releases/download/v0.9.0/nvim.appimage
sudo mv nvim.appimage /usr/bin/nvim
sudo chmod +x /usr/bin/nvim

git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim