#!/usr/bin/env bash

sudo apt install libfuse2

if uname -m | grep -q "aarch64"; then
    wget https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-arm64.appimage
    sudo mv nvim-linux-arm64.appimage /usr/bin/nvim
else
    wget https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-x86_64.appimage
    sudo mv nvim-linux-x86_64.appimage /usr/bin/nvim
fi

sudo chmod +x /usr/bin/nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
