#!/usr/bin/env bash

git config --global user.email "15042748+blalockma@users.noreply.github.com"
git config --global user.name "Mason Blalock"

### Lazygit ###
if uname -m | grep -q "aarch64"; then
    echo "Skipping Lazygit as I need to build from source (arm64 isn't available in releases)"
else
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep '"tag_name":' |  sed -E 's/.*"v*([^"]+)".*/\1/')
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    sudo tar xf lazygit.tar.gz -C /usr/local/bin lazygit
    rm lazygit.tar.gz
    https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.6.1/gcm-linux_amd64.2.6.1.deb
fi

### Git Credential Manager ###
wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb

sudo apt-get update && \
sudo apt-get install -y dotnet-sdk-8.0

dotnet tool install -g git-credential-manager
~/.dotnet/tools/git-credential-manager configure
git config --global credential.credentialStore cache
